AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Prerequisites for Amazon EventBridge Scheduler

Parameters:
  email:
    Type: String
    Default: 'test@email.com'

Resources:
  MySnsTopic:
    Type: AWS::SNS::Topic

  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref email
      Protocol: email
      TopicArn: !Ref MySnsTopic

  SchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sam_scheduler_role
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'scheduler.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'Scheduler_SNS_policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'sns:Publish'
                Resource: !Ref MySnsTopic

Outputs:
  SNStopicName:
    Description: SNS topic name
    Value: !GetAtt MySnsTopic.TopicName

  SNStopicARN:
    Description: SNS topic ARN
    Value: !Ref MySnsTopic

  RoleARN:
    Description: Scheduler role ARN
    Value: !GetAtt SchedulerRole.Arn
